"""
Portfolio Health agent.

This is the agent a novice will hit first when they ask "is everything ok?".
It speaks to MONITOR (where am I right now) and PROTECT (what's the risk
I should know about) — and for a brand-new user with no positions, it
flips into BUILD mode (you're ready to start; here's what to think about).

Inputs: the user's profile + positions (no fetching done here),
the classification (so we know what they actually asked),
and an optional LLM for the narrative summary.

Outputs: an event stream — a streamed plain-language paragraph
for the user, followed by a single structured payload with the metrics.

Tradeoffs
---------
- We do all math from the user's holdings + live prices via market_data.
  If a price is unavailable we degrade: the position contributes by cost
  basis instead of being silently dropped. The structured response flags
  any data gaps so the UI can surface "stale price for X".
- Benchmark: we map the user's `preferred_benchmark` to a real ticker
  and read its trailing return. If we can't, alpha is None and we say so.
- Observations are deliberately short. Surfacing one warning + one
  positive note beats listing 12 metrics that a novice can't act on.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, AsyncIterator

from ..llm import LLMClient, LLMError, assemble_messages, get_llm_client
from ..safety import MODEL_INJECTION_GUARD
from ..market_data import (
    benchmark_ticker,
    get_history_returns,
    get_quote,
    Quote,
)


logger = logging.getLogger(__name__)


DISCLAIMER = (
    "This is not investment advice. Information is generated by an automated "
    "model from your own portfolio data and may be incomplete or out of date. "
    "Always consult a qualified financial advisor before making investment "
    "decisions."
)

CONCENTRATION_HIGH = 0.40
CONCENTRATION_MEDIUM = 0.25


@dataclass
class _PositionMetric:
    ticker: str
    quantity: float
    avg_cost: float
    currency: str
    market_price: float | None
    weight_pct: float
    market_value: float
    pnl_pct: float | None
    sector: str | None


def _round(x: float | None, digits: int = 2) -> float | None:
    if x is None:
        return None
    return round(float(x), digits)


def _portfolio_metrics(positions: list[dict[str, Any]]) -> tuple[list[_PositionMetric], dict[str, Any]]:
    """Compute weights, P&L, sector breakdown. Returns (per-position, summary)."""
    metrics: list[_PositionMetric] = []
    total_value = 0.0
    data_gaps: list[str] = []

    quotes: dict[str, Quote | None] = {}
    for pos in positions:
        ticker = pos["ticker"]
        if ticker not in quotes:
            quotes[ticker] = get_quote(ticker)

    for pos in positions:
        ticker = pos["ticker"]
        qty = float(pos["quantity"])
        avg = float(pos["avg_cost"])
        cur = pos.get("currency", "USD")
        q = quotes.get(ticker)
        price = q.price if q else None
        sector = q.sector if q else None
        if price is None:
            data_gaps.append(ticker)
            value = qty * avg  # fall back to cost basis so weights stay sane
            pnl = None
        else:
            value = qty * price
            pnl = ((price - avg) / avg) * 100.0 if avg > 0 else None

        total_value += value
        metrics.append(
            _PositionMetric(
                ticker=ticker,
                quantity=qty,
                avg_cost=avg,
                currency=cur,
                market_price=price,
                weight_pct=0.0,  # filled in below
                market_value=value,
                pnl_pct=pnl,
                sector=sector,
            )
        )

    if total_value > 0:
        for m in metrics:
            m.weight_pct = (m.market_value / total_value) * 100.0

    metrics.sort(key=lambda m: m.weight_pct, reverse=True)

    summary = {
        "total_value": _round(total_value),
        "position_count": len(metrics),
        "data_gaps": data_gaps,
    }
    return metrics, summary


def _concentration_block(metrics: list[_PositionMetric]) -> dict[str, Any]:
    if not metrics:
        return {
            "top_position_pct": 0.0,
            "top_3_positions_pct": 0.0,
            "flag": "n/a",
            "top_holding": None,
        }
    top = metrics[0].weight_pct / 100.0
    top3 = sum(m.weight_pct for m in metrics[:3]) / 100.0

    if top >= CONCENTRATION_HIGH:
        flag = "high"
    elif top >= CONCENTRATION_MEDIUM:
        flag = "warning"
    else:
        flag = "low"

    return {
        "top_position_pct": _round(top * 100.0),
        "top_3_positions_pct": _round(top3 * 100.0),
        "flag": flag,
        "top_holding": metrics[0].ticker,
    }


def _trailing_return_pct(ticker: str, *, lookback_days: int) -> float | None:
    pts = get_history_returns(ticker, lookback_days=lookback_days)
    if len(pts) < 2:
        return None
    first, last = pts[0].close, pts[-1].close
    if first <= 0:
        return None
    return (last / first - 1.0) * 100.0


def _portfolio_trailing_return(metrics: list[_PositionMetric], *, lookback_days: int) -> float | None:
    if not metrics:
        return None
    weighted: list[tuple[float, float]] = []
    total_w = 0.0
    for m in metrics:
        if m.weight_pct <= 0:
            continue
        r = _trailing_return_pct(m.ticker, lookback_days=lookback_days)
        if r is None:
            continue
        weighted.append((m.weight_pct, r))
        total_w += m.weight_pct
    if total_w <= 0:
        return None
    return sum(w * r for w, r in weighted) / total_w


def _performance_block(metrics: list[_PositionMetric]) -> dict[str, Any]:
    if not metrics:
        return {
            "total_return_pct": None,
            "annualized_return_pct": None,
            "unrealized_pnl_pct": None,
            "lookback_days": 365,
        }

    yearly = _portfolio_trailing_return(metrics, lookback_days=365)
    cost = sum(m.avg_cost * m.quantity for m in metrics)
    market = sum(m.market_value for m in metrics)
    unrealized = ((market - cost) / cost) * 100.0 if cost > 0 else None

    return {
        # `total_return_pct` here is the trailing-year total return on the
        # portfolio's current basket, NOT an account-level realized P&L.
        # Doc'd in README so reviewers don't read it the wrong way.
        "total_return_pct": _round(yearly),
        "annualized_return_pct": _round(yearly),  # 1y == ann. for 1y window
        "unrealized_pnl_pct": _round(unrealized),
        "lookback_days": 365,
    }


def _benchmark_block(
    metrics: list[_PositionMetric],
    *,
    benchmark_name: str | None,
    portfolio_return_pct: float | None,
) -> dict[str, Any]:
    if benchmark_name is None:
        return {"benchmark": None, "benchmark_return_pct": None, "alpha_pct": None}
    ticker = benchmark_ticker(benchmark_name)
    if ticker is None:
        return {"benchmark": benchmark_name, "benchmark_return_pct": None, "alpha_pct": None}
    bench_ret = _trailing_return_pct(ticker, lookback_days=365)
    alpha = None
    if bench_ret is not None and portfolio_return_pct is not None:
        alpha = portfolio_return_pct - bench_ret
    return {
        "benchmark": benchmark_name,
        "portfolio_return_pct": _round(portfolio_return_pct),
        "benchmark_return_pct": _round(bench_ret),
        "alpha_pct": _round(alpha),
    }


def _observations(
    metrics: list[_PositionMetric],
    *,
    concentration: dict[str, Any],
    benchmark: dict[str, Any],
    risk_profile: str | None,
    income_focus: bool,
    has_data_gaps: bool,
) -> list[dict[str, str]]:
    obs: list[dict[str, str]] = []

    # 1) Concentration is almost always the first thing a novice should hear.
    if concentration["flag"] == "high":
        obs.append({
            "severity": "warning",
            "text": f"{concentration['top_position_pct']}% of your portfolio sits in {concentration['top_holding']}. "
                    f"That's a heavy concentration — a single bad print can move your whole account.",
        })
    elif concentration["flag"] == "warning":
        obs.append({
            "severity": "info",
            "text": f"{concentration['top_position_pct']}% of your portfolio is in {concentration['top_holding']}. "
                    f"Worth keeping an eye on if that ever drifts above 40%.",
        })

    # 2) Benchmark commentary, only when we have data
    alpha = benchmark.get("alpha_pct")
    bench_name = benchmark.get("benchmark")
    if alpha is not None and bench_name:
        if alpha > 1:
            obs.append({
                "severity": "info",
                "text": f"You're outperforming {bench_name} by {alpha:.1f}% over the past year.",
            })
        elif alpha < -1:
            obs.append({
                "severity": "info",
                "text": f"You're trailing {bench_name} by {abs(alpha):.1f}% over the past year.",
            })

    # 3) A couple of profile-specific nudges
    if risk_profile == "conservative" and any(
        (m.ticker in {"NVDA", "TSLA", "GME"}) and m.weight_pct > 5
        for m in metrics
    ):
        obs.append({
            "severity": "warning",
            "text": "Your profile is conservative but you're holding meaningful weight in volatile single names. "
                    "Worth checking that this still matches your goals.",
        })

    if income_focus and not any(
        m.ticker in {"VYM", "SCHD", "JNJ", "PG", "KO", "BND", "TLT"}
        for m in metrics
    ):
        obs.append({
            "severity": "info",
            "text": "You've flagged income as a priority but your holdings don't lean on dividend payers. "
                    "A dividend ETF allocation might be worth considering.",
        })

    # 4) Data gap nudge — be honest when prices are missing.
    if has_data_gaps:
        obs.append({
            "severity": "info",
            "text": "Some prices were unavailable from our market data feed; affected positions used cost basis instead.",
        })

    if not obs:
        obs.append({
            "severity": "info",
            "text": "Nothing flagged. Your portfolio looks balanced relative to your stated risk profile.",
        })
    return obs


def _empty_portfolio_response(user_context: dict[str, Any]) -> dict[str, Any]:
    """The user is KYC-complete with no positions yet — pivot to BUILD."""
    name = user_context.get("name", "there")
    risk = user_context.get("risk_profile", "moderate")
    benchmark = user_context.get("preferences", {}).get("preferred_benchmark", "S&P 500")
    return {
        "agent": "portfolio_health",
        "mode": "build",  # not "monitor" — there's nothing to monitor
        "summary": (
            f"Hi {name} — you're set up but you don't hold any positions yet, "
            "so there's nothing to assess. Given your stated risk profile "
            f"({risk}), a sensible first step is a low-cost broad-market ETF "
            f"(e.g. one tracking {benchmark}) and a small bond allocation, "
            "sized to whatever monthly amount you can commit to consistently."
        ),
        "next_steps": [
            "Decide a monthly amount you can commit consistently — starting small is fine.",
            f"Pick one diversified equity ETF tracking a broad index ({benchmark} is common for your profile).",
            "Add a small bond / cash buffer so you're not forced to sell on a bad day.",
        ],
        "concentration_risk": {
            "top_position_pct": 0.0,
            "top_3_positions_pct": 0.0,
            "flag": "n/a",
            "top_holding": None,
        },
        "performance": {
            "total_return_pct": None,
            "annualized_return_pct": None,
            "unrealized_pnl_pct": None,
        },
        "benchmark_comparison": {
            "benchmark": benchmark,
            "benchmark_return_pct": None,
            "alpha_pct": None,
        },
        "observations": [
            {"severity": "info", "text": "You don't have any positions yet — start small and stay consistent."},
        ],
        "disclaimer": DISCLAIMER,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def assess(user_context: dict[str, Any]) -> dict[str, Any]:
    """Pure synchronous compute. Returns the structured response.

    The async streaming entrypoint reuses this and just adds an LLM-narrated
    intro on top.
    """
    positions = user_context.get("positions") or []
    if not positions:
        return _empty_portfolio_response(user_context)

    metrics, summary = _portfolio_metrics(positions)
    concentration = _concentration_block(metrics)
    perf = _performance_block(metrics)
    benchmark_name = (
        user_context.get("preferences", {}).get("preferred_benchmark")
    )
    benchmark = _benchmark_block(
        metrics,
        benchmark_name=benchmark_name,
        portfolio_return_pct=perf["total_return_pct"],
    )

    income_focus = bool(user_context.get("preferences", {}).get("income_focus"))
    obs = _observations(
        metrics,
        concentration=concentration,
        benchmark=benchmark,
        risk_profile=user_context.get("risk_profile"),
        income_focus=income_focus,
        has_data_gaps=bool(summary["data_gaps"]),
    )

    return {
        "agent": "portfolio_health",
        "mode": "monitor",
        "summary_stats": summary,
        "top_holdings": [
            {
                "ticker": m.ticker,
                "weight_pct": _round(m.weight_pct),
                "market_value": _round(m.market_value),
                "currency": m.currency,
                "pnl_pct": _round(m.pnl_pct),
                "sector": m.sector,
            }
            for m in metrics[:5]
        ],
        "concentration_risk": concentration,
        "performance": perf,
        "benchmark_comparison": benchmark,
        "observations": obs,
        "disclaimer": DISCLAIMER,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def format_portfolio_assessment_plain(structured: dict[str, Any]) -> str:
    """Readable multi-line summary for SSE/UI (alongside machine-friendly JSON)."""
    lines: list[str] = []
    mode = structured.get("mode", "monitor")

    lines.append("PORTFOLIO HEALTH")
    lines.append("")

    if mode == "build":
        lines.append(structured.get("summary", "").strip())
        steps = structured.get("next_steps") or []
        if steps:
            lines.append("")
            lines.append("Suggested next steps:")
            for i, step in enumerate(steps, start=1):
                lines.append(f"  {i}. {step}")
        obs = structured.get("observations") or []
        if obs:
            lines.append("")
            lines.append("Notes:")
            for o in obs:
                sev = str(o.get("severity", "info")).upper()
                lines.append(f"  [{sev}] {o.get('text', '').strip()}")
    else:
        lines.append(f"Mode: {mode}")
        holdings = structured.get("top_holdings") or []
        lines.append("")
        lines.append("Top holdings:")
        if not holdings:
            lines.append("  (none listed)")
        for h in holdings:
            cur = h.get("currency") or "USD"
            lines.append(
                f"  • {h.get('ticker')} — {h.get('weight_pct')}% of portfolio, "
                f"market value ~{h.get('market_value')} {cur}, "
                f"unrealized P/L {h.get('pnl_pct')}%, sector {h.get('sector') or 'n/a'}"
            )

        conc = structured.get("concentration_risk") or {}
        lines.append("")
        lines.append("Concentration:")
        lines.append(
            f"  Status: {conc.get('flag')} | Largest position: {conc.get('top_holding')} "
            f"({conc.get('top_position_pct')}% of portfolio)"
        )

        perf = structured.get("performance") or {}
        lines.append("")
        lines.append("Performance:")
        lb = perf.get("lookback_days")
        lb_txt = f" (~{lb} day lookback)" if lb else ""
        lines.append(
            f"  Total return{lb_txt}: {perf.get('total_return_pct')}% "
            f"| Annualized: {perf.get('annualized_return_pct')}% "
            f"| Unrealized P/L: {perf.get('unrealized_pnl_pct')}%"
        )

        bench = structured.get("benchmark_comparison") or {}
        lines.append("")
        lines.append("Benchmark:")
        if bench.get("benchmark"):
            lines.append(
                f"  vs {bench.get('benchmark')}: benchmark return {bench.get('benchmark_return_pct')}%, "
                f"alpha {bench.get('alpha_pct')}%"
            )
        else:
            lines.append("  No benchmark comparison this run.")

        obs = structured.get("observations") or []
        lines.append("")
        lines.append("Observations:")
        for o in obs:
            sev = str(o.get("severity", "info")).upper()
            lines.append(f"  [{sev}] {o.get('text', '').strip()}")

    lines.append("")
    lines.append("Disclaimer:")
    lines.append(f"  {structured.get('disclaimer', '').strip()}")

    gen_at = structured.get("generated_at")
    if gen_at:
        lines.append("")
        lines.append(f"Generated at: {gen_at}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Streaming wrapper used by the HTTP layer
# ---------------------------------------------------------------------------

NARRATIVE_SYSTEM = """\
You are a portfolio health assistant for novice investors. Speak plainly,
no jargon without context, four sentences max. Open by saying what you see
overall, then call out the single most important thing the user should know,
then close with one practical next step. Do not list every metric — the
structured payload covers that. Do NOT include the regulatory disclaimer.

""" + MODEL_INJECTION_GUARD


def _build_narrative_user_msg(query: str, structured: dict[str, Any]) -> str:
    return (
        f"USER QUERY: {query}\n\n"
        f"STRUCTURED ASSESSMENT (do not repeat verbatim, summarise it):\n{structured}\n"
    )


class PortfolioHealthAgent:
    name = "portfolio_health"

    def _with_readable_message(self, structured: dict[str, Any]) -> dict[str, Any]:
        out = dict(structured)
        out["message"] = format_portfolio_assessment_plain(structured)
        return out

    async def run(
        self,
        *,
        query: str,
        user_context: dict[str, Any],
        classification: dict[str, Any],
        llm: LLMClient | None = None,
        conversation_history: list[dict[str, str]] | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        try:
            structured = assess(user_context)
        except Exception as exc:
            logger.exception("Portfolio Health computation failed")
            yield {"type": "data", "delta": "I couldn't fully read your portfolio just now. "}
            yield {
                "type": "structured",
                "payload": {
                    "agent": self.name,
                    "error": "compute_failed",
                    "message": str(exc),
                    "disclaimer": DISCLAIMER,
                },
            }
            return

        # In tests we pass a plain callable as `llm` (the classifier-style
        # fake). It cannot stream, so we treat anything without `stream_text`
        # as "no LLM available" and fall back to the deterministic intro.
        client = llm if (llm is not None and hasattr(llm, "stream_text")) else _maybe_default_llm()
        if client is not None and not hasattr(client, "stream_text"):
            client = None

        if client is None:
            # No LLM available — fall back to a deterministic intro built
            # from the structured payload. Streaming still works, just without
            # the LLM polish.
            intro = _deterministic_intro(structured)
            for chunk in _split_for_stream(intro):
                yield {"type": "data", "delta": chunk}
            yield {"type": "structured", "payload": self._with_readable_message(structured)}
            return

        hist = list(conversation_history or [])
        if hist and hist[-1].get("role") == "user":
            hist = hist[:-1]
        messages = assemble_messages(
            system=NARRATIVE_SYSTEM,
            history=hist,
            user=_build_narrative_user_msg(query, structured),
        )
        try:
            async for piece in client.stream_text(messages, temperature=0.3, max_tokens=300):
                yield {"type": "data", "delta": piece}
        except LLMError as exc:
            logger.warning("Narrative LLM stream failed: %s", exc)
            intro = _deterministic_intro(structured)
            for chunk in _split_for_stream(intro):
                yield {"type": "data", "delta": chunk}

        yield {"type": "structured", "payload": self._with_readable_message(structured)}


def _maybe_default_llm() -> LLMClient | None:
    try:
        return get_llm_client()
    except Exception:
        return None


def _split_for_stream(text: str, *, chunk_size: int = 32) -> list[str]:
    return [text[i : i + chunk_size] for i in range(0, len(text), chunk_size)]


def _deterministic_intro(structured: dict[str, Any]) -> str:
    if structured.get("mode") == "build":
        return structured.get("summary", "")

    conc = structured["concentration_risk"]
    perf = structured["performance"]
    bench = structured["benchmark_comparison"]

    parts = []
    if conc.get("flag") == "high":
        parts.append(
            f"Your portfolio is heavily concentrated in {conc['top_holding']} "
            f"({conc['top_position_pct']}% of total). "
        )
    elif conc.get("flag") == "warning":
        parts.append(
            f"Your largest position is {conc['top_holding']} "
            f"at {conc['top_position_pct']}% — keep an eye on it. "
        )
    if perf.get("total_return_pct") is not None:
        parts.append(f"Trailing one-year return is {perf['total_return_pct']}%. ")
    if bench.get("alpha_pct") is not None and bench.get("benchmark"):
        sign = "ahead of" if bench["alpha_pct"] >= 0 else "behind"
        parts.append(
            f"That puts you {abs(bench['alpha_pct']):.1f}% {sign} {bench['benchmark']}."
        )
    if not parts:
        parts.append("Portfolio looks balanced — see the structured payload below for the numbers.")
    return "".join(parts).strip() or "Portfolio summary attached."
